name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate release
        uses: deltek-sst/deltek-cloud-release-validate-action@v1
